# Site Settings
title: Site Title
tagline: Site Tagline
email: your-email@domain.com
description: >
  The website description
baseurl: "/bulma-clean-theme"
url: ""

paginate: 5
paginate_path: "/blog/page:num"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/ 

livereload: true

sass:
  style: compressed
  source_dir: _sass